# Generated by Django 5.0.6 on 2024-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateField()),
                ('ticket_time', models.TimeField()),
                ('status', models.BooleanField()),
                ('card_status', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'appointment_tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60)),
                ('job_title', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('examination_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'examinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalCards',
            fields=[
                ('medcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fullname', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('workplace_position', models.TextField(blank=True, null=True)),
                ('patient_privileges', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'medical_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionists',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60)),
                ('job_title', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'receptionists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_for_visits', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cabinet', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('examination_type', models.TextField()),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'specializations',
                'managed': False,
            },
        ),
    ]
